// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltjjaomrflsznqgtfsgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amphb21yZmxzem5xZ3Rmc2doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODcxMjMsImV4cCI6MjA2MDM2MzEyM30.dVjUh-7rrSepZaNlvqsjMzwbag8-RhqO9JgwRmikdgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);