// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const createSupabaseClient = (SUPABASE_URL: string, SUPABASE_PUBLISHABLE_KEY: string) => {
    const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
    return supabase;
}